### PR TITLE
New png file for slider

### LINKED ISSUE #4: List of Technologies
# (List all Relevant Front/Back-End Technologies that we learned in Cohort 26)

### Necessary information to include (planning 

Provide a representation of the following technologies

* [x] HTML
* [x] CSS
* [x] JavaScript
* [x] Visual Studio Code
* [x] Git
* [x] GitHub
* [x] npm
* [x] JSON Server
* [x] Grunt
* [x] Browserify
* [x] jQuery
* [x] React
* [x] C#
* [x] ASP.NET
* [x] SQL
* [ ] SQLite
* [ ] Visual Studio

### Design notes (design team)

* [ ] If pictures are used to display the technologies, the names of each must still be visible by default, without having to click/hover.
* [ ] Scrolling bar of learned technologies under class photo like [Cohort 19](https://nss-c19-website.github.io/Class-Page/)
* [ ] (design requirement 2)
* [ ] (design requirement 3)

(copy and paste more lines as needed)

### PR DESCRIPTION
**Pull request by Shu52**
# Description
Changed png file fixes#4  SQLite icon seemed redundant with SQL
## Type of change
Changed both png files
Added width to div devIcons to show text
change to agency css from the build from gulp
- [x] New feature (a non-breaking change which adds functionality)
# Testing Instructions
`git fetch --all` and checkout the branch `git checkout ss-Slider`
in the terminal inside project directory class-website, do `http-server -o`
the web browser should run the current build with the addition of the icon slider below class picture

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by leedyrj — CHANGES_REQUESTED** [review]
Any names that drop to two lines are getting cut off.  We tested and changing .devIcons to a height of 175 px should fix it!

**Review by ncox2011 — CHANGES_REQUESTED** [review]
The second line of the tech names are getting cut off.

**Review by leedyrj — COMMENTED** [review]
Also could you add the link to the tech button on the navbar to link to your slider?

**Review by leedyrj — CHANGES_REQUESTED** [review]
Could you pull up where the link goes to a little bit.  Its dropping below the pictures

**Review by ncox2011 — CHANGES_REQUESTED** [review]
The slider looks great!  When I click the link for Tech it seems to be too far down and only shows the second line of words

**Comment by awieckert** [comment]
👍

**Pull request merged**
