### PR TITLE
added brett and some missing bios

### PR DESCRIPTION
**Pull request by leedyrj**
# Description

added brett and some missing bios/links

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

Please describe the tests required to verify your changes. Provide instructions so PR Tester can check functionality. Please also list any relevant details for your tests

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by leedyrj — COMMENTED** [review]
@awieckert I change where Adelaide moved yet.  I tried a few things, but didn't want to mess with however you redid the columns.  Could you take a look at getting her centered?

**Comment by sdana** [comment]
Blue font color for headlines at bottom of page has disappeared again. Other than that everything looks good to me.

**Review by leedyrj — COMMENTED** [review]
@Shu52  @ncox2011 

Added Aaron's site.  Anyone want to make sure I didn't break it?

**Review by ncox2011 — APPROVED** [review]
It looks good.  Brett is there and Aaron's link works.

**Review by leedyrj — COMMENTED** [review]
@ncox2011 @Shu52 

Will shortened his bio.  I'm going to merge at 11, so if you want to look look quick!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Pull request merged**
